[font]
size = 15.0

# to make the Shift+Enter as Enter
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[[keyboard.bindings]]
key = "J"
mods = "Control"
chars = "\u001b[106;5u"
